---
title: "R Markdown Keyboard Shortcuts!"
author: "Marium Tapal"
date: "27/10/2020"
output: html_document
---

## 1. Insert new code chunk

Mac: option + cmd + I

Windows/Linux: ctrl + alt + I

## 2. Insert pipe operator (%>%)

Mac: cmd + shift + M

Windows/Linux: ctrl + shift + M

## 3. Run current code (line)

Mac: cmd + return/enter

Linux: ctrl + enter

```{r eval=FALSE}
# example
library(nycflights13)
head(flights)
```

## 4. Knit document

Mac: cmd + shift + K

Windows/Linux: ctrl + shift + K

## 5. Insert assignment operator

Mac: option + -

Windows/Linux: alt + -

## 6. Find in Files

Mac: cmd + shift + F

Windows/Linux: ctrl + shift + F

## Other non-markdown specific but useful

### Find 

Mac: cmd + F

Windows/Linux: ctrl + F

### Zoom in 

Mac: cmd + +

Windows/Linux: ctrl + +

### Zoom out

Mac: cmd + -

Windows/Linux: ctrl + -

### Undo

Mac: cmd + Z

Windows/Linux: ctrl + Z

### Cut

Mac: cmd + X

Windows/Linux: ctrl + X

### Copy

Mac: cmd + C

Windows/Linux: ctrl + C

### Paste

Mac: cmd + V

Windows/Linux: ctrl + V

### Save

Mac: cmd + S

Windows/Linux: ctrl + S

... and more

# Find a more extensive list:

In RStudio, go to the **Tools** menu and then **Keyboard Shortcuts Help** or visit this [link](https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts).
